### ISSUE TITLE
Bug "Browse files" Version 0.4

### ISSUE THREAD

**Issue by Coolmicro** [DocMarty84/koozic#1]
Bonjour Nicolas,
J'ai mis à jour avec la version 0.4.
Apparemment, "Browse files" ne fonctionne plus. J'obtiens cette erreur :

Odoo Erreur (côté interface)
Uncaught Error: QWeb2: Template 'oomusic.Browse' not found
https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:2908
Retraçage :
Error: QWeb2: Template 'oomusic.Browse' not found
    at Object.exception (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:2908:7)
    at Engine._render (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:2952:103)
    at Engine.render (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:2948:151)
    at Class.start (https://koozic.xxx.com/web/content/6092-3fa92ba/web.assets_backend.js:2805:556)
    at Class.prototype.(anonymous function) [as start] (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:3009:559)
    at Object.<anonymous> (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:3112:963)
    at Object.<anonymous> (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:547:681)
    at fire (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:546:198)
    at Object.<anonymous> (https://koozic.xxx.com/web/content/6086-dce17a1/web.assets_common.js:547:874)

Nota : j'ai remplacé l'adresse de mon serveur par koozic.xx.com

Merci pour ton travail

**Comment by DocMarty84** [comment]
Salut,

Pour mettre à jour: /odoo-bin -u web -d koozic --stop-after-init

(attention au -u web)

**Comment by Coolmicro** [comment]
Salut,
J'ai bien utilisé la commande de mise à jour avec -u web que tu avais mise en gras et rouge sur le site.
Je n'ai apparemment aucune erreur, ni lors de la mise à jour, ni lorsque je lance le serveur.
Tout fonctionne normalement, sauf "Browse files"
Cordialement

**Comment by DocMarty84** [comment]
Salut

Peux-tu vérifier que le fichier "oomusic/static/src/xml/browse.xml" est bien présent et contient ceci : https://github.com/DocMarty84/oomusic/blob/master/static/src/xml/browse.xml

Peux-tu également essayer d'accéder à ton serveur en ajoutant "debug=assets" : https://koozic.xxx.com/web?debug=assets#view_type=form&...

Peux-tu également nettoyer le cache du navigateur ?

**Comment by Coolmicro** [comment]
Salut,
Merci à toi.
Le fichier browse.xml était bien là et correct.
Mais en vidant le cache (ce à quoi je n'avais pas pensé comme un 
idiot...) tout est rentré dans l'ordre et je peux naviguer par "Browse 
files". Cela dit, ma collection étant complètement taggée, j'utilise 
plutôt genre => artiste => album.
J'en profite pour te signaler 2 petits trucs pour une éventuelle future 
mise à jour :
* Dans "Browse files", il faudrait si possible faire un classement 
alphabétique croissant par défaut.
* Dans les playlists ou dans les albums, c'est un classement 
alphabétique des numéros de pistes, et non numérique : lorsque les 
pistes sont du type 1, 2, 3, etc au lieu de 01, 02, 03 etc les pistes 
10, 11, 12 sont entre 1 et 2. Bien sûr, il est toujours possible de 
retagger correctement, mais... (j'avoue que je n'ai jamais été très 
attentif à ce point, les logiciels que j'utilise traitant de la même 
manière 1, 2, 3 et 01, 02, 03)
Encore merci pour ton suivi, et pour Koozic que j'utilise au quotidien
Cordialement
Michel

**Comment by DocMarty84** [comment]
Salut,

> Dans "Browse files", il faudrait si possible faire un classement alphabétique croissant par défaut.

Tu me confirmes que les titres ne sont pas classés correctement, par contre les dossiers devraient l'être. Ça sera réglé avec https://github.com/DocMarty84/oomusic/commit/c9c0628e761ae3cecde4ff655b746c5efb114c2e

* Dans les playlists ou dans les albums, c'est un classement alphabétique des numéros de pistes, et non numérique

Oui, effectivement. Je vais réfléchir pour améliorer ça, le problème principal étant qu'on ne sait jamais ce qu'on va trouver dans un tag "Numéro de piste". Parfois, on trouve "01", parfois "1", parfois "01/12". Mais bon, c'est pas impossible à régler :)

**Comment by DocMarty84** [comment]
> Dans les playlists ou dans les albums, c'est un classement alphabétique des numéros de pistes, et non numérique

Ça devrait être réglé avec https://github.com/DocMarty84/oomusic/commit/1881ba648bb6b8ba71b7386212869eba4ae36184
Par contre, ça sera pour la 0.5.0.

**Comment by Coolmicro** [comment]
Salut
Merci pour ta réactivité. J'attendrai sagement la version 0.5 ;-)
@+
Michel

**Comment by DocMarty84** [comment]
@Coolmicro : pour info, la v0.4.1 est dispo : https://koozic.net/releases/koozic-v0.4.1.zip

Dans le cas d'une révision mineure (0.4.0 -> 0.4.1), il suffit juste de:
- stopper le serveur
- remplacer les sources
- relancer

Pas de "-u web" ou "-u oomusic" à faire

**Comment by DocMarty84** [comment]
@Coolmicro : j'ai oublié de dire que la v0.4.1 corrigeait "Dans "Browse files", il faudrait si possible faire un classement alphabétique croissant par défaut."

**Comment by Coolmicro** [comment]
Super, merci, ça fonctionne impec.
@+
Michel
