### ISSUE TITLE
Database parameters

### ISSUE THREAD

**Issue by jprenaudet** [DocMarty84/koozic#12]
First, thank you for you work on koozic. I was searching an alternative to subsonic,airsonic... and koozic looks exactly what I'm searching for.

Reading the documentation i didn't find these parameters :
- database name
- database user
- database user password
- IP of database
- port of database

I'm not a big fan of cli parameters as everybody who has to the server can read the systemctl file, so maybe /etc/odoo.conf is a better place to add them if not already exist.

**Comment by DocMarty84** [comment]
Hello,

Indeed, a configuration file would be better. I added it in the [backlog](https://trello.com/b/qF9sVXo3/koozic-development) for the next release.

If you want to switch to a config file, you can do the following:
- Stop the service if already started: `systemctl stop koozic@{}.service` (replace {} by the koozic user)
- Open `/etc/systemd/system/koozic@.service`
- Copy the `ExecStart=...` line
- **As the koozic user**, execute the line but add `--save` at the end of the CLI. Stop with Ctrl + C.
- A file `~/.odoorc` should have been created (in the home directory of the koozic user)
- You can now remove the all the CLI parameters of the `ExecStart=...` line (do not forget to reload properly), and edit the file `~/.odoorc`.

The lines you are looking for are:
```
db_host = False
db_password = False
db_port = False
db_user = False
```

Do not modify `db_name` (= database name), its expected value is `koozic11`.

Each time you change the file, restart koozic with `systemctl restart koozic@{}.service`

Let me know if you face any problem. You can also run `<path_to_binary>odoo-bin --help` for details on all the parameters. Here is a copy-paste for reference:
```
Usage: odoo-bin [options]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit

  Common options:
    -c CONFIG, --config=CONFIG
                        specify alternate config file
    -s, --save          save configuration to ~/.odoorc (or to
                        ~/.openerp_serverrc if it exists)
    -i INIT, --init=INIT
                        install one or more modules (comma-separated list, use
                        "all" for all modules), requires -d
    -u UPDATE, --update=UPDATE
                        update one or more modules (comma-separated list, use
                        "all" for all modules). Requires -d.
    --without-demo=WITHOUT_DEMO
                        disable loading demo data for modules to be installed
                        (comma-separated, use "all" for all modules). Requires
                        -d and -i. Default is none
    -P IMPORT_PARTIAL, --import-partial=IMPORT_PARTIAL
                        Use this for big data importation, if it crashes you
                        will be able to continue at the current state. Provide
                        a filename to store intermediate importation states.
    --pidfile=PIDFILE   file where the server pid will be stored
    --addons-path=ADDONS_PATH
                        specify additional addons paths (separated by commas).
    --load=SERVER_WIDE_MODULES
                        Comma-separated list of server-wide modules.
    -D DATA_DIR, --data-dir=DATA_DIR
                        Directory where to store Odoo data

  HTTP Service Configuration:
    --http-interface=HTTP_INTERFACE
                        Listen interface address for HTTP services. Keep empty
                        to listen on all interfaces (0.0.0.0)
    -p PORT, --http-port=PORT
                        Listen port for the main HTTP service
    --longpolling-port=PORT
                        Listen port for the longpolling HTTP service
    --no-http           Disable the HTTP and Longpolling services entirely
    --proxy-mode        Activate reverse proxy WSGI wrappers (headers
                        rewriting) Only enable this when running behind a
                        trusted web proxy!

  Web interface Configuration:
    --db-filter=REGEXP  Regular expressions for filtering available databases
                        for Web UI. The expression can use %d (domain) and %h
                        (host) placeholders.

  Testing Configuration:
    --test-file=TEST_FILE
                        Launch a python or YML test file.
    --test-report-directory=TEST_REPORT_DIRECTORY
                        If set, will save sample of all reports in this
                        directory.
    --test-enable       Enable YAML and unit tests.
    --test-commit       Commit database changes performed by YAML or XML
                        tests.

  Logging Configuration:
    --logfile=LOGFILE   file where the server log will be stored
    --logrotate         enable logfile rotation
    --syslog            Send the log to the syslog server
    --log-handler=PREFIX:LEVEL
                        setup a handler at LEVEL for a given PREFIX. An empty
                        PREFIX indicates the root logger. This option can be
                        repeated. Example: "odoo.orm:DEBUG" or
                        "werkzeug:CRITICAL" (default: ":INFO")
    --log-request       shortcut for --log-handler=odoo.http.rpc.request:DEBUG
    --log-response      shortcut for --log-
                        handler=odoo.http.rpc.response:DEBUG
    --log-web           shortcut for --log-handler=odoo.http:DEBUG
    --log-sql           shortcut for --log-handler=odoo.sql_db:DEBUG
    --log-db=LOG_DB     Logging database
    --log-db-level=LOG_DB_LEVEL
                        Logging database level
    --log-level=LOG_LEVEL
                        specify the level of the logging. Accepted values:
                        ['info', 'debug_rpc', 'warn', 'test', 'critical',
                        'debug_sql', 'error', 'debug', 'debug_rpc_answer',
                        'notset'].

  SMTP Configuration:
    --email-from=EMAIL_FROM
                        specify the SMTP email address for sending email
    --smtp=SMTP_SERVER  specify the SMTP server for sending email
    --smtp-port=SMTP_PORT
                        specify the SMTP port
    --smtp-ssl          if passed, SMTP connections will be encrypted with SSL
                        (STARTTLS)
    --smtp-user=SMTP_USER
                        specify the SMTP username for sending email
    --smtp-password=SMTP_PASSWORD
                        specify the SMTP password for sending email

  Database related options:
    -d DB_NAME, --database=DB_NAME
                        specify the database name
    -r DB_USER, --db_user=DB_USER
                        specify the database user name
    -w DB_PASSWORD, --db_password=DB_PASSWORD
                        specify the database password
    --pg_path=PG_PATH   specify the pg executable path
    --db_host=DB_HOST   specify the database host
    --db_port=DB_PORT   specify the database port
    --db_sslmode=DB_SSLMODE
                        specify the database ssl connection mode (see
                        PostgreSQL documentation)
    --db_maxconn=DB_MAXCONN
                        specify the the maximum number of physical connections
                        to posgresql
    --db-template=DB_TEMPLATE
                        specify a custom database template to create a new
                        database

  Internationalisation options. :
    Use these options to translate Odoo to another language. See i18n
    section of the user manual. Option '-d' is mandatory. Option '-l' is
    mandatory in case of importation

    --load-language=LOAD_LANGUAGE
                        specifies the languages for the translations you want
                        to be loaded
    -l LANGUAGE, --language=LANGUAGE
                        specify the language of the translation file. Use it
                        with --i18n-export or --i18n-import
    --i18n-export=TRANSLATE_OUT
                        export all sentences to be translated to a CSV file, a
                        PO file or a TGZ archive and exit
    --i18n-import=TRANSLATE_IN
                        import a CSV or a PO file with translations and exit.
                        The '-l' option is required.
    --i18n-overwrite    overwrites existing translation terms on updating a
                        module or importing a CSV or a PO file.
    --modules=TRANSLATE_MODULES
                        specify modules to export. Use in combination with
                        --i18n-export

  Security-related options:
    --no-database-list  Disable the ability to obtain or view the list of
                        databases. Also disable access to the database manager
                        and selector, so be sure to set a proper --database
                        parameter first

  Advanced options:
    --dev=DEV_MODE      Enable developer mode. Param: List of options
                        separated by comma. Options : all,
                        [pudb|wdb|ipdb|pdb], reload, qweb, werkzeug, xml
    --shell-interface=SHELL_INTERFACE
                        Specify a preferred REPL to use in shell mode.
                        Supported REPLs are: [ipython|ptpython|bpython|python]
    --stop-after-init   stop the server after its initialization
    --osv-memory-count-limit=OSV_MEMORY_COUNT_LIMIT
                        Force a limit on the maximum number of records kept in
                        the virtual osv_memory tables. The default is False,
                        which means no count-based limit.
    --osv-memory-age-limit=OSV_MEMORY_AGE_LIMIT
                        Force a limit on the maximum age of records kept in
                        the virtual osv_memory tables. This is a decimal value
                        expressed in hours, and the default is 1 hour.
    --max-cron-threads=MAX_CRON_THREADS
                        Maximum number of threads processing concurrently cron
                        jobs (default 2).
    --unaccent          Use the unaccent function provided by the database
                        when available.
    --geoip-db=GEOIP_DATABASE
                        Absolute path to the GeoIP database file.

  Multiprocessing options:
    --workers=WORKERS   Specify the number of workers, 0 disable prefork mode.
    --limit-memory-soft=LIMIT_MEMORY_SOFT
                        Maximum allowed virtual memory per worker, when
                        reached the worker be reset after the current request
                        (default 671088640 aka 640MB).
    --limit-memory-hard=LIMIT_MEMORY_HARD
                        Maximum allowed virtual memory per worker, when
                        reached, any memory allocation will fail (default
                        805306368 aka 768MB).
    --limit-time-cpu=LIMIT_TIME_CPU
                        Maximum allowed CPU time per request (default 60).
    --limit-time-real=LIMIT_TIME_REAL
                        Maximum allowed Real time per request (default 120).
    --limit-time-real-cron=LIMIT_TIME_REAL_CRON
                        Maximum allowed Real time per cron job. (default:
                        --limit-time-real). Set to 0 for no limit.
    --limit-request=LIMIT_REQUEST
                        Maximum number of request to be processed per worker
                        (default 8192).
```

**Comment by DocMarty84** [comment]
In case you would like to try, this will setup Koozic to use the `~/.odoorc` file:

```
curl https://raw.githubusercontent.com/DocMarty84/koozic/11.0-config/extra/installer/koozic_install.py > k_install.py
chmod +x k_install.py
sudo ./k_install.py install
```

So you just have to edit the `~/.odoorc` file and un-comment the necessary lines.

**Comment by jprenaudet** [comment]
Waouh !! Thank for the quick answer and all the details. That's great.  
I'll try that probably this week-end. I will tell you if every goes well.  
Thanks again.

**Comment by jprenaudet** [comment]
So I tested today, not fully, but here are some comments about my first install.

Again, you've done a amazing work on koozic.

First, I have use your install script to test and after that, I switch to `ansible` (I use it on my server for all installation).
My goal was to first install postgresql, create database and user and after install koozic.

About the installation script :
- The installation script give me a warning about `python3-num2words` not installed, so I add it to the packages (not sure if this is relevant)
- Permissions for `.odoorc` and `koozic-install.conf ` are 644, making them readable for everyone -> I suggest to make them 640.

About database security :  
Correct me if I'm wrong : In your install script you create a user for koozic who is superuser. At koozic startup, you try to create a empty database for koozic with koozic user.  
With my type of installation I don't want to create a new superuser on my database (less power is always a good thing :) ).
Here is my suggestion :
- In the `setup_postgresql` function of install script :
  - First create the database for koozic : s.call('su - postgres -c "CREATE DATABASE koozic11 ENCODING "unicode" TEMPLATE template1'.shell=True)
  - After create a user without specific privilege : s.call('su - postgres -c "createuser {}"'.format(self.user), shell=True).
  - Give user privilege on database : s.call('su - postgres -c "grant all privileges on database koozic11 to {}"'.format(self.user), shell=True)
- In koozic code :
  - replace `_create_empty_database` by checking if user can connect to koozic database.

Thanks again for the support!
Hope this can help.

**Comment by DocMarty84** [comment]
Thanks for the feedback!

> The installation script give me a warning about `python3-num2words` not installed, so I add it to the packages (not sure if this is relevant)

This one is not relevant, no problem.

> Permissions for `.odoorc` and `koozic-install.conf` are 644, making them readable for everyone -> I suggest to make them 640.

I guess they are created with the default umask of your system. But indeed, it could be changed for security reason. Especially the `.odoorc`, which could contain the DB password. It could probably be 600.

> In your install script you create a user for koozic who is superuser.

Indeed, I did it for easiness. I'll have a look at your suggestion to avoid it. Hopefully I will have run the necessary tests to make sure it works on all supported platforms within a day or two.

Note that if you manually execute what you mention before the install script, the script should not override your setup:
- the user is already created, so it should not be modified
- `_create_empty_database` won't do anything if the DB name already exists: https://github.com/DocMarty84/koozic/blob/8864d16c246acb80f454891f46f86f9809a966f5/odoo/cli/start.py#L64

However I didn't test this, so I can't ensure this at 100 %.

**Comment by jprenaudet** [comment]
En lisant d'autres issues je me suis rendu compte que tu parlais francais donc je switch de langues --> plus facile pour moi :) !

Concernant l'utilisateur postgresql : 
- ca fonctionne si dans pg_hba.conf je mets `host  all  <db_user>  ...`
- le but aurais été de mettre : `host  <db_name>  <db_user>  ...`
Mais en workaround c'est parfait.

**EDIT** : J'ai corrigé le problème ci-dessous --> Pb de config des limit_memory_*
J'ai rencontré 1 autre problème ensuite (vu que ca dérive un peu du sujet original, dis moi si tu préfères que je créé une autre issue ou si on continue sur celle là) :
Quand je met le paramètre `workers` à une valeur différentes de zéro, j'obtiens cette erreur :
```
Traceback (most recent call last):
  File "/opt/koozic/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/opt/koozic/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/opt/koozic/odoo/cli/server.py", line 175, in run
    main(args)
  File "/opt/koozic/odoo/cli/server.py", line 169, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "/opt/koozic/odoo/service/server.py", line 991, in start
    rc = server.run(preload, stop)
  File "/opt/koozic/odoo/service/server.py", line 391, in run
    self.start()
  File "/opt/koozic/odoo/service/server.py", line 380, in start
    self.httpd.serve_forever()
  File "/usr/lib/python3/dist-packages/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/usr/lib/python3/dist-packages/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 1223, in init_socket
    self.update_environ()
  File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 1235, in update_environ
    name = socket.getfqdn(address[0])
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 307, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 280, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "/usr/lib/python3/dist-packages/gevent/resolver_thread.py", line 67, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/usr/lib/python3/dist-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/lib/python3/dist-packages/gevent/threadpool.py", line 175, in spawn
    self.adjust()
  File "/usr/lib/python3/dist-packages/gevent/threadpool.py", line 136, in adjust
    self._adjust_step()
  File "/usr/lib/python3/dist-packages/gevent/threadpool.py", line 116, in _adjust_step
    self._add_thread()
  File "/usr/lib/python3/dist-packages/gevent/threadpool.py", line 145, in _add_thread
    start_new_thread(self._worker, ())
RuntimeError: can't start new thread
```
Aurais tu une idée ?

1 dernière question :
- Je n'ai pas bien compris le foctionnement des transcoders : Comment est choisi le transcoder aproprié ?
Sous Firefox, j'ai l'impression que peu importe les transcoders existant, il choisi toujours opus.
Sous Dsub, si je n'ai pas de transcoder avec `output_format=mp3`, alors pas de transcodage :
 - Du coup petite FR : j'aurais adoré avoir la possibilté de choisir le format de sortie (en l'occurence ogg), par example le premier transcoder de la liste serait celui choisi par défaut.

Sinon, c'est franchement un plaisir en termes de rapidité, facilité d'utilisation.. Ca change de libre/air/sub...sonic !

**Comment by DocMarty84** [comment]
> Concernant l'utilisateur postgresql 

Je vais jeter un œil à ça... Par contre, le but de l'installer est de rendre les choses le plus simples possibles, et "que ça marche partout". Je peux toujours ajouter des infos dans la doc pour les cas plus spécifiques.

> EDIT : J'ai corrigé le problème ci-dessous --> Pb de config des limit_memory_*

Je ne suis pas certain de bien comprendre : tu as corrigé le problème lié à `can't start new thread` ? Ça peut effectivement venir de la limite mémoire qui n'est pas suffisante. Si `limit_memory_hard` est trop bas, la mémoire ne sera pas suffisante pour créer un nouveau thread. Normalement, le script d'installation essaie d'être suffisamment malin pour que le nombre de workers soit adapté à la mémoire de la machine.

> Je n'ai pas bien compris le foctionnement des transcoders

C'est la deuxième fois que j'ai cette question, il va falloir que je fasse quelque chose :-)

Sur un navigateur web, le format est forcé : opus en priorité, puis ogg et finalement mp3 en fallback :

https://github.com/DocMarty84/oomusic/blob/8e9a578ebec13fdbf8f1e3a1bafeef09606aae72/models/oomusic_track.py#L164

L'ordre des transcoders n'a d'importance que si il y en a plusieurs du même format. Par exemple, tu pourrais définir un "Opus haute qualité" et un "Opus basse qualité". Le premier de la liste sera choisi en priorité.

Ça pourrait valoir le coup de rendre ça un peu plus flexible. D'un autre côté, je ne vois pas de beaucoup de raisons de choisir autre chose que Opus : c'est le mieux supporté sur les navigateurs, et il est top niveau qualité. Le risque est que certains utilisateurs aillent configurer un transcoder par défaut pour un format qui ne soit pas pris en charge correctement par leur navigateur. Bon après, ça serait pas très compliqué à faire... Un truc dans le style devrait être suffisant : https://gist.github.com/DocMarty84/6a2078ecd016b5719d1b64d9960b3cdd

En passant, dans le cas de Firefox, y'a une petite astuce pour contourner un problème que j'arrive pas à résoudre : https://github.com/DocMarty84/koozic/issues/9#issuecomment-412192240

Sur DSub (ou tout autre client), le format choisi va normalement dépendre de ce que l'application va demander. Je pense que l'application demande systématiquement du mp3, du coup c'est ce que tu reçois. Par défaut, si aucun format n'est spécifié, on prend mp3 :

https://github.com/DocMarty84/oomusic/blob/8e9a578ebec13fdbf8f1e3a1bafeef09606aae72/controllers/subsonic/media_retrieval.py#L38

Là, c'est surtout une question de compatibilité avec les applications. Je crains que renvoyer autre chose que du mp3 pose plus de problèmes que ça n'en résout.

**Comment by jprenaudet** [comment]
> Je vais jeter un œil à ça... Par contre, le but de l'installer est de rendre les choses le plus simples possibles, et "que ça marche partout".

Je comprends l'idée, pas de souci.

> Je ne suis pas certain de bien comprendre : tu as corrigé le problème lié à can't start new thread ? 

C'est complètement ca. En fait j'install koozic dans un conteneur lxc. Dans ce type de conteur les valeurs `nb_cpus`, `ram` sont celle du host et non du conteneur. En les retouchant à la main, je me suis planté d'un facteur 1024  :sweat_smile: !

>  Sur un navigateur web, le format est forcé : opus en priorité, puis ogg et finalement mp3 en fallback

Ok j'ai compris le principe. Ca me parait sain comme manière de faire.

> Par défaut, si aucun format n'est spécifié, on prend mp3

J'ai vérfié, DSub ne demande pas de format, d'où le fallback en mp3. Là encore, je comprendds pourquoi tu as fait ce choix de mp3. Mais comme je suis un peu tétu, je me suis fait un petit post install script pour faire du fallback en ogg (je change ces 3 lignes) :
```
/opt/koozic/addons/oomusic/controllers/subsonic/media_retrieval.py :
 output_format = kwargs.get('format', 'mp3') --> 'ogg'

/opt/koozic/addons/oomusic/controllers/subsonic/common.py :
            transcodedContentType='audio/mpeg',  --> 'audio/ogg'
            transcodedSuffix='mp3',              --> 'ogg'
```

Ca ma permis de voir une petit erreur. Dans le fichier `/opt/koozic/addons/oomusic/controllers/subsonic/common.py` ligne 217, a priori le `path` devrait être le chemin du fichier en relatif par rapport au dossier de musique source et non juste le nom du fichier. J'ai trouver cette issue sur ampache qui en parle https://github.com/ampache/ampache/issues/1213#issuecomment-216035916.

Encore merci pour tout. Mes problèmes sont résolu, je te laisse fermer l'issue si ca te va !

**Comment by DocMarty84** [comment]
> Ok j'ai compris le principe. Ca me parait sain comme manière de faire.

Je réfléchis tout de même à ajouter la fonctionnalité avec https://github.com/DocMarty84/oomusic/commit/7af24631591207085cd090e67d258453f8d7c26e C'est pas définitif, mais ça pourrait être intégré dans la prochaine version.

> Ca ma permis de voir une petit erreur.

Merci, c'est corrigé avec https://github.com/DocMarty84/oomusic/commit/0171f2c1c15c27a94724c6012cbe84b13256a5e6

> Encore merci pour tout. Mes problèmes sont résolu, je te laisse fermer l'issue si ca te va !

Super si tout tourne bien chez toi ! Je dois dire que je suis toujours partagé entre l'idée d'ajouter des options de configuration ou laisser un configuration simple qui fonctionne chez tout le monde. L'avantage c'est que le système est suffisamment flexible pour pouvoir l'adapter facilement.

**Comment by jprenaudet** [comment]
> Je dois dire que je suis toujours partagé entre l'idée d'ajouter des options de configuration ou laisser un configuration simple qui fonctionne chez tout le monde.

C'est toujours le grand problème ! Ce qu'on voit le plus régulièrement c'est une partie `advance settings`. Tu mets des valeurs par défaut et si quelqu'un veut le changer c'est à ses risques et périls. Mais bon c'est pas l'idéal... Ca veut aussi dire plus de tests, plus de confs à maintenir...

J'ai vu un autre petit problème... (je pense que c'est le dernier cette fois !).  
Dans la fonction [make_child_track](https://github.com/DocMarty84/oomusic/blob/7c99234975482581f21431a025d5697a4bf7a8ed/controllers/subsonic/common.py#L204), il manque le renvoi du covertArt. j'ai corrigé ca en rajoutant 
```
if track.folder_id.image_medium:
    elem_track.set('coverArt', str(track.folder_id.id))
```

Mais ca amène un plus gros problème : Je me suis rendu compte que quand tu parse les ID3 tags, tu ne récupère pas le covertArt. J'avoue que je ne me sers pas de fichier type `folder.jpg`. Ca pourrait être intéressant à rajouter...

**Comment by DocMarty84** [comment]
> je pense que c'est le dernier cette fois !

Houlà, il en reste sûrement encore plein d'autres :D

> il manque le renvoi du covertArt.

Réglé avec https://github.com/DocMarty84/oomusic/commit/ba6d6f623113832f466e0024e65b5ecac0923a2a

(ça m'a enfin permis de comprendre pourquoi l'image de l'album ne s'affichait pas dans DSub)

> tu ne récupère pas le covertArt.

Ajouté avec https://github.com/DocMarty84/oomusic/commit/b8f3330dc0c583085103e4defe7772ac18d679e0

Si tu as l'occasion d'appliquer le patch chez toi et de me faire un retour, ça serait sympa car moi j'exporte systématiquement les covers avec Clementine.

Merci pour ton feedback en tous cas !

**Comment by jprenaudet** [comment]
Je viens de tester à l'instant :

>  DocMarty84/oomusic@0171f2c

Ok tout est bon, DSub créé bien les bons répertoires

> DocMarty84/oomusic@ba6d6f6

C'est parfait, DSub affiche bien les pochettes

> DocMarty84/oomusic@b8f3330

Mon préféré, tout marche nickel :+1: 

Joli boulot :smiley:
