### ISSUE TITLE
FR: Add a way to play albums directly

### ISSUE THREAD

**Issue by gerroon** [DocMarty84/koozic#14]
Hi

So I am in Album view and I want to play the whole album witha  single click. It seems like this is not possible, I can go into the album and click ona song but that only plays a single song and it definetely does not add  or replace to the current playlist.

Please add a way to play anj album directly by either replacing the current playlist or adding to the current playlist but start playing from the album.

I propose that the there could be a play icon in the middle of the thumbnail in album view list, and clicking on it will play the album.

**Comment by DocMarty84** [comment]
Hello,

Indeed, you always have to go through the playlist. I will add this suggestion to the roadmap.

-------- Message d'origine --------

**Comment by DocMarty84** [comment]
Damn, all the formatting of my message was lost. I'll answer in a couple of days when I have access to a computer...

-------- Message d'origine --------
