### ISSUE TITLE
How to use sqlite?

### ISSUE THREAD

**Issue by gerroon** [DocMarty84/koozic#17]
Hi

I am trying to test v2 py install. I do not want to install one more database on my system so I want to use Sqlite. How do I use it with v2 regular install ?

I installed dependencies and running odoo-bin

**Comment by DocMarty84** [comment]
Hello,

Only PostgreSQL is supported. Unfortunately, there is no plan to support SQLite in the future.

**Comment by gerroon** [comment]
ok thanks
