### ISSUE TITLE
Docker Persistent data? 

### ISSUE THREAD

**Issue by onedr0p** [DocMarty84/koozic#19]
In your install instructions you show how to mount the music directory. But what about the application data? How are we able to keep that persistent? Any time I restart the container my settings vanish.

```docker run -d -p 8069:8069 -p 8072:8072 -v <host_folder>:/mnt/host:ro --name koozic docmarty84/koozic```

**Comment by DocMarty84** [comment]
Normally, they are persistent. `docker run...` should be run once; then, you should use `docker stop` and `docker start`.

**Comment by onedr0p** [comment]
I'd like to be able to store the persistent data on my NFS share, instead of on the VM it is running on.

**Comment by DocMarty84** [comment]
Unfortunately, it's not possible in v1 since the KooZic and PostgreSQL are running on the same container.

For v2, there is a higher chance to be able to make it work. Indeed, in v2 KooZic and PostgreSQL are split in 2 different containers. In that case, I guess it's possible to imagine the v2 KooZic container connecting to a PostgreSQL installation on your NFS share. I'll have a look if I can find a solution.

**Comment by reinierkors** [comment]
Is it possible to add a volume to mount the postgreSQL db and make it persistent?
./postgres-data:/var/lib/postgresql/data

This would mean we don't need two different containers.

**Comment by DocMarty84** [comment]
> Is it possible to add a volume to mount the postgreSQL db and make it persistent?
> ./postgres-data:/var/lib/postgresql/data
> 
> This would mean we don't need two different containers.

I'm not sure that would work.

For v2, I'll go for separate containers using Docker Compose, which makes things easier. Here are 2 solutions.

## Solution 1

Mount the PostgreSQL Unix socket folder `/var/run/postgresql`. The main drawback of this solution is that the UID used to run KooZic in the container must match the UID of a user on the PostgreSQL server.

What you need to do is the following.

### On the PostgreSQL server

1. Create a specific user on the PostgreSQL server
```
adduser koozic
su - postgres -c "createuser -s koozic"
id -u koozic
```

### On the Docker host

1. Mount the PostgreSQL Unix socket folder `/var/run/postgresql` on the host machine. I don't really know what is a good solution in this case, maybe SSHFS.
2. In the `Dockerfile` of the archive [solution_1.zip](https://github.com/DocMarty84/koozic/files/2776492/solution_1.zip) attached, change the line `usermod -u <user_id> koozic && \` to set the `user_id` retrieved at step 1.
3. In the `docker-compose.yml` file, change `/music` to the folder you want to mount.
4. Run:

```
docker-compose build
docker-compose up -d
```

## Solution 2

Connect remotely to PostgreSQL. It requires some configuration on the PostgreSQL server, but it is a more robust solution.

### On the PostgreSQL server

1. Create the `koozic` user and set a password (in this case, the password is `koozic`):

```
sudo -i
su - postgres -c "createuser -s koozic"
su - koozic -c "createdb koozic-v2"
su - koozic
psql koozic-v2
koozic-v2=# ALTER USER koozic WITH PASSWORD 'koozic';
koozic-v2=# \q
```

2. Make PostgreSQL listen to all addresses. Modify `postgresql.conf` and add:
```
listen_addresses = '*'
```

3. Accept remote logins. Add the following to `pg_hba.conf`:
```
host    all             all              0.0.0.0/0                       md5
host    all             all              ::/0                            md5
```

4. Restart PostgreSQL: `service postgresql restart`
5. Add the necessary `iptables` rules to accept incoming connections to port `5432`. For testing, you can simply do `iptables -P INPUT ACCEPT` to accept all incoming connections, but that's obviously not advised for a production setup.

### On the Docker host

In the archive [solution_2.zip](https://github.com/DocMarty84/koozic/files/2776493/solution_2.zip) attached:

1. In `entrypoint.sh`, replace `<postgres_ip_address>` with the IP address of the PostgreSQL server
2. In the `docker-compose.yml` file, change `/music` to the folder you want to mount.
3. Run:

```
docker-compose build
docker-compose up -d
```

**Comment by DocMarty84** [comment]
Hum, I forgot to add the filestore part to the previous solution. All the configuration is stored on the database, but thumbnails are stored on the disk, by default on `/home/<user>/.local/share/Odoo/filestore/koozic-v2`. So you will also need to mount this volume. I'll update the solution above soon.
