### ISSUE TITLE
Une suggestion pour une future version

### ISSUE THREAD

**Issue by Coolmicro** [DocMarty84/koozic#2]
Salut,
J'ai pensé à un truc sympa. Serait-il possible de décider dans la configuration si Artist va désigner l'artiste de la plage, ou l'artiste de l'album.
La raison de ce souhait est que les amateurs de musique classique donnent souvent une signification différente au tag "Artiste de la plage", d'ailleurs souvent appelé "Interprète" dans les logiciels de tag et à "Artiste de l'album". Etant donné que le champ "Compositeur" n'est quasiment jamais utilisé par les logiciels de lecture, je mets en général le compositeur également dans "Artiste de l'album", et je mets les interprètes dans "Artiste de la plage" (je ne suis pas le seul à faire ça...). Et du coup, je préfère que "Artiste de l'album" soit mis en avant dans les recherches...
Ce n'est qu'une suggestion, si c'est compliqué, laisse tomber...
Cordialement

**Comment by DocMarty84** [comment]
Salut,

Merci pour la suggestion. C'est vrai que c'est un choix arbitraire de définir l'artiste de l'album comme étant l'artiste de la première piste. Ça fonctionne les albums d'un artiste, mais dans le cas de compilations ou de titres de compositeurs classiques, ça ne colle pas.

C'est pas trop compliqué à faire, je verrai ça pour la v0.5.0

**Comment by DocMarty84** [comment]
En fait, plutôt que d'en faire une option, on peut simplement définir l'artiste d'un album comme ceci :
- si "Album Artist" est défini pour la première plage, on le choisit comme artiste de l'album
- sinon, "Artist" de la première plage sera choisi comme artiste de l'album

Ça me parait assez logique.

**Comment by Coolmicro** [comment]
Salut,
Oui, ça serait très bien comme ça.
@+
Michel

**Comment by Coolmicro** [comment]
Salut,
Toujours dans la même veine que mes messages précédents concernant le tri par pistes, lesquelles ont des numéros de formes diverses, je viens de m'apercevoir que le tri ne tient pas compte du n° de disque. Il faudrait que l'ordre de tri tienne d'abord compte du n° de disque s'il est présent, puis du n° de piste, dans les cas où il y a 2 disques, ou plus, pour le même album.  Pour le moment, pour des pistes correctement numérotées, on a 01, 01, 02, 02 , 03, 03 etc quand il y a 2 disques dans le même album.

**Comment by DocMarty84** [comment]
Yep, j'ai revu certaines logiques de tri, ça ne devrait plus poser problème

**Comment by DocMarty84** [comment]
Réglé avec la v0.5.0 dans https://github.com/DocMarty84/oomusic/commit/d670e48dd36d851675ed528817f099d3088ada9e
