### ISSUE TITLE
Odoo Server Error - Missing Record

### ISSUE THREAD

**Issue by gerroon** [DocMarty84/koozic#21]
Docker compose install, everything works except when I try to add music library, it shows that there are files in the fodler, I get this error when I press save or scan.

```
Odoo Server Error - Missing Record
Missing document(s):One of the documents you are trying to access has been deleted, please try again after refreshing. 

```

**Comment by gerroon** [comment]
I think the database portion is not using the set volume

I am not using then default in there so i have


```
volume:
- /media/DRIVE/koozic/db:/var/lib/postgresql 

```

When I run the container, this folder is not populated at all.

**Comment by DocMarty84** [comment]
Are you trying to use an external PostgreSQL database? Can you provide the docker files you are using? `/media/DRIVE/koozic/db:/var/lib/postgresql` doesn't seem correct.

**Comment by DocMarty84** [comment]
You can also refer to https://github.com/DocMarty84/koozic/issues/19#issuecomment-455856478
