### ISSUE TITLE
docker-compose pull errors out?

### ISSUE THREAD

**Issue by gerroon** [DocMarty84/koozic#23]
Hi

I am trying to update the docker install. So I do docker-compose pull but gives me this error below?

I already have a docker compose version running. And I did not change the yml file except adding my music volume? Did the repo disappear?

docker-compose pull
Pulling db  ... done
Pulling app ... error

ERROR: for app  pull access denied for koozic_app2, repository does not exist or may require 'docker login'                                                                                  
ERROR: pull access denied for koozic_app2, repository does not exist or may require 'docker login'

**Comment by DocMarty84** [comment]
Hello,

You need to use `docker-compose build`. See the [installation instructions](https://koozic.net/installation/#Docker).

**Comment by gerroon** [comment]
Well I am not sure, that does not seem to get the latest images

**Comment by DocMarty84** [comment]
Just go to https://github.com/DocMarty84/koozic/releases/latest , and download / extract "koozic-v2.0.0-docker.tar.gz". This will download the latest version of KooZic.

**Comment by gerroon** [comment]
Not sure if I articulated well, I meant that "docker-compose build" does not do anything, it does not seem to pull any new docker images. I am not sure what my version is but I have not upgraded it for a while and your latest  version is 3 days old.

Btw I copied the latest docker-compose.yml to my original one ( I have couple volumes there) So in theory it should update it. But that is based on the assumption that my version is a bit old and there are some new updated Docker images from you.

**Comment by DocMarty84** [comment]
> your latest version is 3 days old

Keep in mind it is a beta version.

Here is what I did to simulate an update:
1. Download v2.0.0 at https://github.com/DocMarty84/koozic/releases/download/v2.0.0/koozic-v2.0.0-docker.tar.gz
2. Edit “docker-compose.yml” and replace “/music” by the music folder I want to share.
3. Build: `docker-compose build`
4. Run: `docker-compose up -d`

At this point, I can access http://localhost:8069.

5. Stop KooZic: `docker-compose stop`
6. Download v2.1.0-beta.1 at https://github.com/DocMarty84/koozic/releases/download/v2.1.0-beta.1/koozic-v2.1.0-beta.1-docker.tar.gz
7. Copy the `Dockerfile` from v2.1.0-beta.1 to the folder where I extracted v2.0.0.
8. Build: `docker-compose build` > a new version of KooZic is downloaded
9. Run: `docker-compose up -d`

When I access http://localhost:8069, it is updated correctly (Go to Music > Configuration > Settings, you'll see the version running).

**Comment by gerroon** [comment]
HI

Thanks for the detailed reply. My version see,s to be v2.0.0 so I was right about not updating. 

After you described your steps, I think my missing step was the docker file not the compose file. I will try it when around my server again.

Thanks again.
