### ISSUE TITLE
dsub doesn't connect to v2

### ISSUE THREAD

**Issue by lbeltrame** [DocMarty84/koozic#24]
Testing the latest v2 release, dsub tries to access:

```
/rest/getLicense.view?u=USER&p=enc:PASSWORD&v=1.2.0&c=DSub"
```

However it gets back a 403. I've confirmed it's not an issue of the reverse proxy (also going directly has the same error).

**Comment by lbeltrame** [comment]
Ok, using the username will *not* work. It needs an email address if it is set.

**Comment by DocMarty84** [comment]
Hello,

Indeed, you need to use the email address: https://screenshots.firefox.com/Sh91TJRgn5D92Q9M/demo.koozic.net
The same that you are using to connect to the web interface.
