### ISSUE TITLE
CSRF validation failed on path '/web/login'

### ISSUE THREAD

**Issue by gerroon** [DocMarty84/koozic#25]
Hi

I just wiped my volumes and restarted this using docker-compose build then up Now I cant login after I changed my login :( 

This is the erro I get

`koozic_app | 2019-02-22 22:24:20,820 25 WARNING koozic-v2 odoo.http: CSRF validation failed on path '/web/login'`

**Comment by gerroon** [comment]
Will running another Odoo docker andn using the same browser make this issue arise?

**Comment by DocMarty84** [comment]
Hello,

As long as the hostname or IP address is different, that shouldn't be a problem. If both your volumes had the same IP address, you might want to clear the cache and clear the cookies, just in case.

If you face the 'CSRF validation failed' error, just try to go to the home page (http://host:port/) and log in again. This can also arise if you let the '/web/login' page opened for too long: the token has a limited lifetime, so if you wait too much time, login might fail. If it happens, just go to the homepage.

**Comment by gerroon** [comment]
Ok thanks amn I will try it.
