### ISSUE TITLE
New UI hints are awesome

### ISSUE THREAD

**Issue by DavidVentura** [DocMarty84/koozic#29]
Hey, I didn't find a way to send you a message - this is not an issue.
I've upgraded my old koozic install to the current latest and the 'tutorial' hints on first login are excellent! How did you do those?

Keep up the good work!

**Comment by DocMarty84** [comment]
Thanks! These are provided by the Odoo framework in the [web_tour](https://github.com/odoo/odoo/tree/12.0/addons/web_tour) module. Creating such tours is then quite easy:

https://github.com/DocMarty84/oomusic/blob/c183b528e3d2a35f746b8ec5aab32988c12053a4/static/src/js/tour.js
