### ISSUE TITLE
Petit bug version 0.7

### ISSUE THREAD

**Issue by Coolmicro** [DocMarty84/koozic#3]
Bonjour,
Avec la maj, j'obtiens une erreur d'affichage du media player avec le message me signalant qu'il ne trouve pas le css.
Je me suis aperçu que le dossier /addons/oovideo/static/src/css avait été appelé less par erreur. De même les extensions des fichiers css dans le dossier étaient less au lieu de css.
En remplaçant less par css, tout est rentré dans l'ordre.
Merci pour cette nouvelle version
Cordialement

**Comment by DocMarty84** [comment]
Salut,

Hum, c'est étrange, le fait que cela s'appelle "less" est bien normal. Peux-tu essayer en nettoyant le cache du navigateur ? Car cela me fait penser au problème que tu avais rencontré dans #1.

**Comment by Coolmicro** [comment]
Salut,

Ma foi, j'avais bien nettoyer le cache du navigateur, et j'avais un 
message me disant qu'il ne trouvait pas le fichier media_player.css. En 
ayant renommé, tout semble bien fonctionner maintenant. Je ne peux pas 
en dire plus. Si le nommage des fichiers avec une extension less et du 
dossier en less est normal (alors qu'avant, c'était css => j'ai vérifié, 
je garde toujours une sauvegarde du dossier du programme en cas de mise 
à jour), alors ne tient pas compte de ma remarque.

Cordialement

Michel

------ Message d'origine ------
De: "DocMarty84" <notifications@github.com>
À: "DocMarty84/koozic" <koozic@noreply.github.com>
Cc : "Coolmicro" <coolmicro@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 06/09/2017 19:19:38
Objet : Re: [DocMarty84/koozic] Petit bug version 0.7 (#3)

**Comment by DocMarty84** [comment]
La partie musique fonctionne correctement ? C'est bizarre que la partie video pose problème, alors que la partie musique ne pas de problème. Les 2 parties utilisent "less" à présent. Tu as essayé avec un autre navigateur, à tout hasard ?

A tester : 
- passer en mode debug:  https://koozic.xxx.com/web?debug=assets#view_type=form&...
- update plus global ./odoo-bin -u web -d koozic --stop-after-init

Merci pour ton retour !

**Comment by Coolmicro** [comment]
Je ferai les tests demain soir, en remettant less, avec d'autres 
navigateurs (là, c'état Vivaldi, mon navigateur habituel)
Ce n'étais pas la partie vidéo qui déconnait (je ne l'utilise pas), 
c'était seulement l'affichage du player musique.
@+


------ Message d'origine ------
De: "DocMarty84" <notifications@github.com>
À: "DocMarty84/koozic" <koozic@noreply.github.com>
Cc : "Coolmicro" <coolmicro@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 06/09/2017 20:49:37
Objet : Re: [DocMarty84/koozic] Petit bug version 0.7 (#3)

**Comment by Coolmicro** [comment]
Salut,

Après tests, je te confirme le problème précédemment évoqué. Pour que tu 
comprennes bien, je te joins 2 copies écran, tests effectués dans 2 
navigateurs totalement "vierges" et donc sans cache (une version 
portable de Firefox, et Microsoft Edge que je n'utilise jamais...)
* avec_mise_a_jour_sans_modif_de_fichiers.jpg : mise à jour effectuée 
sans rien modifier, donc en gardant le "less" : tu vois que le player ne 
s'affiche pas correctement et que j'obtiens un message indiquant que 
media_player.css n'est pas trouvé
* avec_mise_a_jour_APRES_modif_des_fichiers.jpg : j'ai renommé le 
dossier /oovideo/static/src/less en /oovideo/static/src/css et j'ai 
modifié les extensions de media_player et browse de ce dossier de less 
en css : tu vois que tout s'affiche correctement, et tout fonctionne 
parfaitement

Voilà, je ne peux t'en dire plus...

Cordialement

Coolmicro (Michel)
Coordinateur du groupe Ebooks libres et gratuits

------ Message d'origine ------
De: "DocMarty84" <notifications@github.com>
À: "DocMarty84/koozic" <koozic@noreply.github.com>
Cc : "Coolmicro" <coolmicro@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 06/09/2017 20:49:37
Objet : Re: [DocMarty84/koozic] Petit bug version 0.7 (#3)

**Comment by DocMarty84** [comment]
Salut,

Merci pour les infos. Ce genre de changement ne devrait plus avoir lieu dans les versions futures, mais j'aimerais quand même pouvoir trouver comment résoudre ce genre de souci de façon plus ou moins efficace.

Pourrais-je te demander ta collaboration et exécuter dans le terminal, avec l'utilisateur qui exécute koozic :
```
psql -d koozic -c "select arch_fs,arch_db from ir_ui_view where name like '%account%';" &> query1.txt
psql -d koozic -c "select name,index_content from ir_attachment where name like '%assets_backend.%css';" &> query2.txt
tar cfz query.tar.gz query1.txt query2.txt
```

Cela va créer un fichier "query.tar.gz" qui m'aidera à comprendre ce qui se passe. Pas de soucis, ça ne contient que des infos techniques, aucune info perso (tu peux le vérifier par toi-même, quoique le fichier "query2.txt" est probablement un peu gros, de l'ordre de 10-15 Mo).

Pourrais-tu l'envoyer par email à `nicolas.martinelli@gmail.com` ?

Merci

**Comment by DocMarty84** [comment]
Résolu avec `./odoo-bin -i oomusic,oovideo -d koozic --stop-after-init`
