### ISSUE TITLE
Error Automatic installation

### ISSUE THREAD

**Issue by moblesmarti** [DocMarty84/koozic#32]
Hi, I try to install it with the official script on Ubuntu 18.04 following your instructions:

wget https://raw.githubusercontent.com/DocMarty84/koozic_install/v2/koozic_install.py -O koozic_install.py
sudo python3 koozic_install.py install

**But I have this error...**

Installing pip dependencies...
Downloading the latest KooZic version...
Traceback (most recent call last):
  File "koozic_install.py", line 725, in <module>
    install(args)
  File "koozic_install.py", line 680, in install
    driver.download_and_extract()
  File "koozic_install.py", line 65, in download_and_extract
    tarfile.open(name=out_file.name).extractall(path=dir)
  File "/usr/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

I install it on VM Proxmox

Thanks in advance for any help

**Comment by DocMarty84** [comment]
Hello.

It fails at the creation of a temporary file. Do you have write access to /tmp?

**Comment by moblesmarti** [comment]
I download it on home user folder, no in temp folder, but I'll try to download it on temp folder

**Comment by DocMarty84** [comment]
No no, that's not what I meant. The installer creates a file in `/tmp`. Maybe you don't have access to the folder.

You can change the following to the install script: https://gist.github.com/DocMarty84/c7baa151c7843c177eb936f9ff787707

Just replace `/PATH/TO/FILE.tar.gz` to a path you can write to, e.g. `/home/USER/koozic.tar.gz`

**Comment by moblesmarti** [comment]
I have made the appropriate modifications indicated and now I get the following error.

Installing pip dependencies...
Downloading the latest KooZic version...
Traceback (most recent call last):
  File "koozic_install.py", line 725, in <module>
    install(args)
  File "koozic_install.py", line 680, in install
    driver.download_and_extract()
  File "koozic_install.py", line 64, in download_and_extract
    out_file.write(requests.get(DOWN_URL).content)
TypeError: write() argument must be str, not bytes

Theoretically I have permissions all permissions

**Comment by moblesmarti** [comment]
![Termius_-_114](https://user-images.githubusercontent.com/12881456/63452952-d5c9b900-c447-11e9-86c8-fb970e9b0740.jpg)

**Comment by DocMarty84** [comment]
My bad, sorry, it should be `wb`. I updated https://gist.github.com/DocMarty84/c7baa151c7843c177eb936f9ff787707

**Comment by moblesmarti** [comment]
![Termius_-_114](https://user-images.githubusercontent.com/12881456/63455860-e8df8780-c44d-11e9-8d65-08cfd671edfd.jpg)

Now the first error!

**Comment by DocMarty84** [comment]
Hum... I'm very sorry, I made a stupid mistake. I forgot to attach the files to the new release on Github. It should now be solved.

**Comment by moblesmarti** [comment]
Yes, now I have installed it.

Thanks for your help.

**Comment by DocMarty84** [comment]
I hope you'll enjoy it. Don't hesitate to ask if you have any question.
