### ISSUE TITLE
Error service to run on boot

### ISSUE THREAD

**Issue by moblesmarti** [DocMarty84/koozic#33]
Hi, I have this error on koozic@.service

Failed to start koozic@.service: Unit name koozic@.service is missing the instance name.
See system logs and 'systemctl status koozic@.service' for details.

Failed to get properties: Unit name koozic@.service is neither a valid invocation ID nor unit name.

**koozic@.service file**
[Unit]
Description=KooZic - Open Source Streaming Software
Documentation=https://koozic.net/
After=network.target

[Service]
User=%i
ExecStart=/opt/koozic-v2/odoo-bin
Restart=on-failure
ProtectSystem=full

[Install]
WantedBy=multi-user.target

**Comment by DocMarty84** [comment]
What is the user used to run KooZic? By default, it is `root`, so you should do: `systemctl status syncthing@root.service` or `service koozic@root status`.

**Comment by moblesmarti** [comment]
The problem is that restarting the server does not start with the system. Because the service gives an error.

![Termius_-__011__KooZic](https://user-images.githubusercontent.com/12881456/63844023-b1119c00-c987-11e9-9681-96dd6081a2d3.png)

**Comment by DocMarty84** [comment]
How did you enable the service? You should do: `systemctl enable koozic@root.service` (replace `root` by the koozic user is you set one).

Then: `systemctl start koozic@root.service`

**Comment by moblesmarti** [comment]
Thanks, it was an error on user.
