### ISSUE TITLE
Music folder not sticking, disappears after "Scan" pressed

### ISSUE THREAD

**Issue by bubblesnout** [DocMarty84/koozic#34]
I'm running Koozic via Docker using the instructions on the website. Everything looks fine, I can log in and change my password etc. 

I set up the music folder to /mnt/host, which is exactly where I have mounted my local music folder in docker-compose.yml. I save the folder and it appears to stick, however as soon as I click in to it and click "Scan" the list of folders is now empty and no scan occurs. I can repeat over and over, no change.

I have verified the Docker container has access to the files by running a shell to the container and doing ls /mnt/host - I can see all of my artist directories just fine.

koozic.log file is empty and the docker logs don't show anything interesting

What am I doing wrong here?

**Comment by bubblesnout** [comment]
Apologies, weirdly it was a permissions issue. Even though I could see the folder contents when connected via a shell it started working when I allowed "read" permissions to everyone for the music folder. All good!

**Comment by DocMarty84** [comment]
Great you could solve it by yourself! I hope you'll enjoy.
