### ISSUE TITLE
Album art is missing for m4a encoded albums / Question on album art res

### ISSUE THREAD

**Issue by GensHaze** [DocMarty84/koozic#37]
Hello! As I commented on that other issue, I've started using KooZic and so far I'm loving it. I ran into a couple additional roadblocks, but right now I finally have a good setup I can use day to day.

I've just found a minor annoyance, for some reason and after running a full scan, there are some spots within my library where the album art is missing. And definitely, I've easily ruled out as m4a files being some sort of cause for this - all of the missing album art files I've checked are in m4a format. All the mp3 files, as far as I can tell, do show album art.

And also, I wanted to quickly ask... when using KooZic with the Ultrasonic app, it fetches the album art, though, I see this is in a low-res, it looks blurry. Is it possible to increase the res, or is that on the side of Ultrasonic entirely? (I've already tried to disable the Ultrasonic setting to downscale the album art cover, but it appears to be the same still)

These m4a files are a big part of my collection, and I've manually tagged most of my library with corresponding art, so it's kind of a let down not to be able to enjoy the album covers on their entire glory, but that's all. I'm still not opting for a different app or anything, since playback works great, but I wanted to mention these things as possible issues. Thank you!

**Comment by DocMarty84** [comment]
Hello,

Could you please send me one of the m4a files at the email address you'll find at [1] (*@pm.me*) so I have an example to work on?

Regarding the album art resolution, I am aware of it, it should be quite easy to solve.

[1] https://github.com/DocMarty84/koozic/commit/c8ecfb2b72c734546950d6a74b4a9487e9b79eda.patch

**Comment by DocMarty84** [comment]
Hello,

Both issues are fixed in the above revisions. My plan is to release these fixes with v3 of KooZic, but it is not ready yet. If you want, you can easily apply these patches on your installation:

```
sudo -i
cd /opt/koozic-v2/addons/oomusic
curl https://gist.githubusercontent.com/DocMarty84/52ecfd37000329905debcf30c55bba2a/raw/b7f1c85d3414e6f31ce6eab184ee1863dd94b8a4/issue_37.diff | patch -p1
systemctl restart koozic@root.service
```

You might want to clear the cache of your browser (Ctrl + F5) and of Ultrasonic to retrieve the cover arts in good definition.

**Comment by GensHaze** [comment]
Thank you so much once again :) I've just applied the patch and it works great now!
