### ISSUE TITLE
Minor UI question: Suggestions

### ISSUE THREAD

**Issue by GensHaze** [DocMarty84/koozic#38]
Hello once again,

Just decided to put in another issue for another little thing I noticed in the UI. On the landing page for KooZic, Suggestions, I find these two buttons at the very top, Save and Discard:

![image](https://user-images.githubusercontent.com/56946907/67661202-341e8680-f926-11e9-8694-2da9d3419bb3.png)

Which I don't find too much sense of. Clicking on save just seems to save another instance of... the same page? Was just wondering if those should be removed. Everything else is working fine.

I figure knowing the backend for Odoo these should be easy to remove, but unfortunately I'm not familiar. Either way they're pretty harmless, still, so nothing urgent by any means. Thanks for all your hard work.

**Comment by DocMarty84** [comment]
Hello,

Yep, I know that. Unfortunately, that's something standard which comes with the Odoo framework. Getting rid of it would be quite a lot of hassle in comparison to the harm it does (it practice, it can do nothing bad).

I'm always trying to have the best balance between feature and code complexity: if a feature is too complex to implement for what it would bring to the software, then I don't implement it. It allows me to keep the codebase clean and easily maintainable on a long term.

So unfortunately, at the moment I don't plan to remove these buttons.

**Comment by GensHaze** [comment]
Thank you for the detailed explanation! I'll go ahead and close this then, not sure if it should be tagged, if you're tracking it or anything like that.
