### ISSUE TITLE
Album art on .opus files

### ISSUE THREAD

**Issue by GensHaze** [DocMarty84/koozic#40]
Hi again!

I've been very happy with my Koozic installation for these couple months now, just stumbled upon a minor aesthetic detail here. As I keep a lossy library myself, I've decided further encodings from FLAC would be directly in opus from here on out, so I've started to add them besides my current mp3 and m4a files. But it looks like Koozic doesn't get the cover art from them properly:

![imagen](https://user-images.githubusercontent.com/56946907/72053876-861c4a80-328d-11ea-9727-9c682f0650f1.png)

Playback is all fine, so it's mostly just that. I'll be happy to send a test .opus file if necessary. Thanks!

EDIT: Whoops, forgot to mention that I attempted to upgrade my Koozic installation, as well as force a full scan with no change, in case it's useful.

**Comment by DocMarty84** [comment]
Hello,

That's great to know you like it! We can do the same like in https://github.com/DocMarty84/koozic/issues/37#issuecomment-546824610 , and I'll have a look!

Note that the v3 is not released yet, but I'll see to include this fix in it. I'll also provide a patch for your version.

**Comment by DocMarty84** [comment]
Hello,

With the patch https://github.com/DocMarty84/koozic/issues/37#issuecomment-547077349 applied, this should make the trick:

```
sudo -i
cd /opt/koozic-v2/addons/oomusic
curl https://gist.githubusercontent.com/DocMarty84/973d6baca39b713cf98813cafd87d0af/raw/165eb8e39c27bd189db11dec5df23575b4de4047/issue_40.diff | patch -p1
systemctl restart koozic@root.service
```

Let me know if you face any problem.

**Comment by GensHaze** [comment]
They are now showing cover art, everything's perfect now. Very grateful for all your work, thanks! Will go ahead and close this one as well then. :) Cheers.
