### ISSUE TITLE
Play next Song

### ISSUE THREAD

**Issue by aroundmyroom** [DocMarty84/koozic#5]
in what way is Play Next Song supported? right now after a song is played there is no next song
(I do not use playlist (yet)), cause it takes me too much time.
I like the application to play all files found in the same "sub"folder so that it can play an album even if it is not  identified as album and not added to a playlist

**Comment by DocMarty84** [comment]
It is only supported through the playlists. You can add a complete folder to a playlist quite easily: https://drive.google.com/file/d/1h0nm3aRKFTH3FtScd_dRz7c7vOB0L8jb/view?usp=sharing
