### ISSUE TITLE
External ID not found in the system: web.login

### ISSUE THREAD

**Issue by ghost** [DocMarty84/koozic#8]
First, I'd like to thank you for your hard work on Koozic!

I ran the installer for the latest version on Debian 9. Upon hitting the IP on port 8069, I receive the following:

```
2018-05-11 04:31:05,209 24860 INFO koozic werkzeug: 127.0.0.1 - - [11/May/2018 04:31:05] "GET /web/login HTTP/1.1"500 -
2018-05-11 04:31:05,218 24860 ERROR koozic werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/koozic/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/koozic/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/koozic/odoo/http.py", line 1316, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/koozic/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/koozic/odoo/http.py", line 1480, in dispatch
    result = ir_http._dispatch()
  File "/opt/koozic/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/opt/koozic/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/koozic/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/koozic/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/koozic/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/koozic/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/koozic/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/opt/koozic/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/koozic/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/koozic/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/opt/koozic/odoo/http.py", line 1267, in flatten
    self.response.append(self.render())
  File "/opt/koozic/odoo/http.py", line 1260, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/koozic/odoo/addons/base/ir/ir_ui_view.py", line 1189, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/koozic/odoo/addons/base/ir/ir_ui_view.py", line 1096, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/opt/koozic/odoo/addons/base/ir/ir_model.py", line 1332, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/opt/koozic/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup

  File "/opt/koozic/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/koozic/odoo/addons/base/ir/ir_model.py", line 1312, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.login
```

Did I miss a step?

**Comment by DocMarty84** [comment]
Hello,

From the log, I'd say that you tested with the beta version, right? Can you confirm you ran:
`curl https://raw.githubusercontent.com/DocMarty84/koozic/11.0/extra/installer/koozic_install.py > k_install.py`
(11.0 is important)

**Comment by ghost** [comment]
I had used the beta, yes. I'm a little confused with the numbering, then. I don't see 11.0 in any of the releases, and the installation docs on the koozic website use 10.0. The "download" section also mentions "The latest version is KooZic v0.8.0." I had figured that it was just using a really old version so I figured the beta was where I should go.

**Comment by ghost** [comment]
Hm, I just ran the uninstaller, had it delete the files/drop the DB, and then ran the 11.0 installer (with -u koozic). I'm still getting the same error.

**Comment by DocMarty84** [comment]
Can you please copy-paste the complete result of the installation process (including the command you type, e.g. ./k_installer -u koozic)? I guess something went wrong at some point.

**Comment by DocMarty84** [comment]
BTW, any other information on your system can be helpful: language, locale, Python version, pip packages...

When I test the installer on an OS, I use the lightest version, in English. It's usually a server version or a netinstall with the minimum packages installed. I tried once again in a fresh Debian 9 with a user koozic (created thanks to `adduser koozic`), and it worked without problem. I guess there is something on your installation unforeseen, and I would think it's somewhere after `Initializing KooZic...`.

**Comment by ghost** [comment]
```
# ./k_install.py  -u koozic install
Choose your operating system:
  1 : Ubuntu 18.04
  2 : Ubuntu 16.04
  3 : Debian 9
  4 : Fedora 27 / 28
  5 : CentOS 7.4
  6 : ArchLinux
  0 : exit this installer
Your choice: 3
Installing package dependencies...
Installing pip dependencies...

createuser: creation of new role failed: ERROR:  role "koozic" already exists
Downloading the latest KooZic version...
Initializing KooZic...
Created symlink /etc/systemd/system/multi-user.target.wants/koozic@koozic.service → /etc/systemd/system/koozic@.service.

  ___           _        _ _       _   _
 |_ _|_ __  ___| |_ __ _| | | __ _| |_(_) ___  _ __
  | || '_ \/ __| __/ _` | | |/ _` | __| |/ _ \| '_ \
  | || | | \__ \ || (_| | | | (_| | |_| | (_) | | | |
 |___|_| |_|___/\__\__,_|_|_|\__,_|\__|_|\___/|_| |_|
  ____                               __       _ _
 / ___| _   _  ___ ___ ___  ___ ___ / _|_   _| | |
 \___ \| | | |/ __/ __/ _ \/ __/ __| |_| | | | | |
  ___) | |_| | (_| (_|  __/\__ \__ \  _| |_| | |_|
 |____/ \__,_|\___\___\___||___/___/_|  \__,_|_(_)


You can now connect to http://localhost:8069/.
Default credentials:
    Email:    admin
    Password: admin
```

Language/Locale is en_US UTF-8. Python version is default for debian (2.7.13/3.5.3)

```
# pip list --local
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
enum34 (1.0.4)
munkres (1.0.7)
musicbrainzngs (0.5)
mutagen (1.27)
PyYAML (3.11)
speedtest-cli (1.0.6)
Unidecode (0.4.17)
```

Attached is also the result of `dpkg-query -l python*`
[dpkg-query.txt](https://github.com/DocMarty84/koozic/files/1997027/dpkg-query.txt)

**Comment by DocMarty84** [comment]
Damn, no error whatsoever... Let's see what we can find with something more verbose.

As superuser:
- Stop the service:
`systemctl stop koozic@koozic.service`

As user koozic:
- Drop koozic database:
`dropdb koozic`
- Delete the filestore
`rm -rf ~/.local/share/Odoo/`
- Initialize a new installation:
`/opt/koozic/odoo-bin -d koozic -i web,oomusic,oovideo --with-demo=all --stop-after-init --log-level=debug`
- Start manually:
`/opt/koozic/odoo-bin --workers=2 --max-cron-threads=1 --limit-time-cpu=1800 --limit-time-real=3600 --log-level=debug`

Now try to connect and see if it is still crashing. Could you also provide the various outputs you'll get?
Can you also try to clear your browser cache? And see if accessing through `curl` works well:
`curl http://localhost:8069/web/login`

> pip list --local

Could you provide `pip3 list --local`? Thanks

**Comment by aroundmyroom** [comment]
my experience was that after installing and re=installing it was not ok in debian9, similar issue as above . I used a plain vanilla new vm with debian 9 to use the latest version.

**Comment by ghost** [comment]
Running the manual installation worked fine (except the --with-demo flag wasn't found so I omitted it).

I did more testing around and found that dropping the koozic role from postgres and then running the installer fixed it. Is there any reason that koozic requires Superuser, Create role, Create DB privileges?

**Comment by DocMarty84** [comment]
> Running the manual installation worked fine (except the --with-demo flag wasn't found so I omitted it).

Sh*t, that was `--without-demo=all`. Anyway, no problem, just be aware that you now have a user demo (pass: demo) on your system that you might want to delete.

> I did more testing around and found that dropping the koozic role from postgres and then running the installer fixed it. Is there any reason that koozic requires Superuser, Create role, Create DB privileges?

If you Google the error 'External ID not found in the system: web.login', you find a couple of people who faced the problem with Odoo (KooZic is based on Odoo). What is weird is that each person found a different way of solving. Install `python-passlib`, run `-u all`, a bugfix was also made about this... This runs from 2014, and once in a while some guy faces the problem and then it magically disappears. Apparently, you are one of them, and you found a new way of solving it. I'll ask around next week if some of my colleagues have an idea about it...

The only configuration run for PostgreSQL is:
`su - postgres -c "createuser -s <user_name>"`

Nothing really exceptional. If the role already exists, it just fails, but without consequences. You can see it in your log: 
`createuser: creation of new role failed: ERROR:  role "koozic" already exists`

Regarding the privileges, the DB user should be allowed to create a new database (named `koozic`), and obviously create new tables. I've never really got into the details of the user roles for the DB, since the default values seemed to work fine.

**Comment by ghost** [comment]
Thanks for sticking with me through the report. I'd definitely recommend removing all of those privileges from the user and only let it touch its own database.

**Comment by DocMarty84** [comment]
I could consider it, I guess these should not be necessary once the DB is initialized. At least, a warning in the documentation for those who use PostgreSQL for other applications.
